"""empty message

Revision ID: c934cda91b2e
Revises: 
Create Date: 2023-06-07 16:33:16.933503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934cda91b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum(), nullable=True),
    sa.Column('date_released', sa.DateTime(), nullable=True),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('partially_solved', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzles'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('puzzle_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_solved', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_puzzle_scores_puzzle_id_puzzles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_puzzle_scores_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzle_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle_scores')
    op.drop_table('users')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
